[time]
disabled = false

[git_branch]
symbol = "ğŸŒ¿ "

[git_commit]
disabled = false

[git_status]
disabled = false
modified = "âœï¸"
untracked = "?"

[nodejs]
symbol = "â¬¢ "

[directory]
home_symbol = "~"
style = "bold yellow"
truncation_length = 5
truncation_symbol = "ğŸ“‚ "
